[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arithmetic"
version = "0.1.0"
description = "Mathematics of Uncertainty: Uncertain number arithmetic and arithmetic spaces"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Trần Mạnh Cường", email = "tmcuong2408@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools]
packages = ["arithmetic"]

[tool.setuptools.package-dir]
arithmetic = "."
